version: '3.7'
services:
  node-app:
    build: ./artifacts/gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app

  mysql:
    image: mysql:8.0.18
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

