version: '3'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  nodejs:
    image: node:8.16.2-alpine
    build: ./artifacts/gate-simulator
    ports:
      - "9999:9999"
